### ISSUE TITLE
找不到 server\src\handler\gptStreamHandler.js 文件

### ISSUE THREAD

**Issue by mohoho** [ltyzzzxxx/gpt-web-terminal#1]
期待开源 QAQ

**Comment by ltyzzzxxx** [comment]
现在才看到，抱歉小伙伴。可能是之前提交文件时有遗漏吧，已经更名为 gptHandler。若还有问题，麻烦再提一下 Issue 吧。

另外，项目所有文件全部开源，如果有遗漏的，麻烦提醒一下呀～

感谢支持～
