### ISSUE TITLE
调用openAI API也要挂TIZI吗？

### ISSUE THREAD

**Issue by Shawn20** [ltyzzzxxx/gpt-web-terminal#2]
运行 gpt-test-demo 提示 **Error: connect ETIMEDOUT xxxx**

**Comment by ltyzzzxxx** [comment]
对的。这个 gpt-test-demo 主要用于测试你的 🪜 是否能稳定文芳 gpt 服务（部分劣质 🪜 没办法访问），包括之后本地运行 GPT Terminal，也需要你配置好 API Key 并保证网络通畅。
