### ISSUE TITLE
可以添加自定义模型，自定义open代理吗？

### ISSUE THREAD

**Issue by lanzeweie** [ltyzzzxxx/gpt-web-terminal#3]

**Comment by ltyzzzxxx** [comment]
谢谢提醒 ❤️

已经引入通过命令选择 GPT-3.5 / GPT-4 模型的功能。
但还不支持自定义模型，如果有其它好用的模型，可以推荐一下呀，我将其集成进来～
自定义 open 代理的话，可以提供一下代理 API 地址吗？我去测试一下，如果可以的话，我放到自定义配置中。

谢谢 Issue～
