### ISSUE TITLE
感觉部署方面可能需要写的详细一点，小白确实有点难上手。

### ISSUE THREAD

**Issue by KKISO574** [ltyzzzxxx/gpt-web-terminal#4]
他这个后端是单独开了一个端口然后前端把请求转发到这个端口服务上吗，server里面那个config里面需要配置apikey才可以使用GPT对话吧，然后就是我构建后NGINX反向代理请求到后端去好像不能用。，用的香港的服务器，不知道哪里出了问题，请指明。

**Comment by ltyzzzxxx** [comment]
实在抱歉，目前正在改进中，1.x.x 版本的部署方式不再使用，不使用云服务器方式，而是采用网站托管部署方式，后端也会取消数据库，增加 accessToken 访问方式，敬请期待。

谢谢🙏

**Comment by ltyzzzxxx** [comment]
目前已发布最新版本，README 文档中有快速部署方式。
