### ISSUE TITLE
ask

### ISSUE THREAD

**Issue by GeniusTDY** [ltyzzzxxx/gpt-web-terminal#5]
[vite] http proxy error at /chat-process:
Error: connect ECONNREFUSED 127.0.0.1:3002
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)

**Comment by ltyzzzxxx** [comment]
这是在 railway 部署时报的错还是在本地运行时报的错呢？注意如果是本地运行的话，前端和后端都需要启动。请参照 Quick Start 部分。我确定可以运行成功。

**Comment by GeniusTDY** [comment]
> 这是在 railway 部署时报的错还是在本地运行时报的错呢？注意如果是本地运行的话，前端和后端都需要启动。请参照 Quick Start 部分。我确定可以运行成功。

感谢回复，我在确认前后端都启动后再次本地运行时，出现错误：request to https://api.openai.com/v1/chat/completions failed ，然后更改了api接入点后终端正常回复。
想请教一下，我在使用官网的api接入点时，梯子是一直开着的，为什么会连接不上？

**Comment by tychozzz** [comment]
感觉可能是梯子不支持 chatgpt，可以尝试更换一下梯子。还有一种情况是 api key 余额不足，更换一下 api key。

**Comment by GeniusTDY** [comment]
> 感觉可能是梯子不支持 chatgpt，可以尝试更换一下梯子。还有一种情况是 api key 余额不足，更换一下 api key。

web官网的是可以用，余额也是足的，只是官网的api接入点不行，更改了别人搭建的接口地址才能用

**Comment by tychozzz** [comment]
感觉是梯子的问题。那就只能使用 accessToken 的方式访问 ChatGPT 或者用别人的代理。
